DjangoBlog/Accounts/urls.py
from django.conf import urls
from .import views
from django.urls import path
app_name='accounts'
urlpatterns=[
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout')
]

DjangoBlog/DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from articles import views as article_view




urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('',include('articles.urls')),
    path('accounts/',include('Accounts.urls'))

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DjangoBlog/articles/urls.py
from django.conf.urls import url
from django.urls import path
from .import views


app_name = 'article'
urlpatterns = [
    path('create/<str:type>',views.article_create,name='create'),
    path('',views.article_list,name='list'),
    path('export-pdf/<str:export_Format>', views.create_pdf , name="export-pdf"),
    path('export-excel', views.create_excelSheet , name="export-excel"),
    path('export-bibtex', views.create_BibtexSheet , name="export-bibtex"),
    path('bibtexUpload',views.bibtexPopulator, name='bibtex-upload'),
    path('profile',views.ProfilePage, name='profile'),
    path('<str:type>/<str:slug>/edit',views.EditArticle, name="edit-data"),
    path('<str:type>/<str:slug>/delete',views.DeleteArticle, name="delete-data"),
    path('<str:type>/<str:slug>/update',views.UpdateArticle, name = "update_data"),
    url('showArticle/(?P<slug>[\w-]+)',views.article_detail,name='detail'), 
    #name catching block in the url
   
]

DjangoBlog/articles/views.py
from django.db.models import Count,Min,Max 
from enum import auto
from django.http.response import FileResponse, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect, render
from .models import Article,Book,ConferenceArticle, GeneralArticle
from django.contrib.auth.decorators import login_required
from .import forms
from django.contrib import messages
from django.shortcuts import get_object_or_404

import bibtexparser
from bibtexparser.bibdatabase import BibDatabase
from bibtexparser.bwriter import BibTexWriter
import datetime
import csv
import xlwt #for excel export

# import for pdf export--------------------
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from io import BytesIO


from django.template.loader import get_template
from django.urls import reverse

from xhtml2pdf import pisa


#pdf export here-------------------------
def create_pdf(request,export_Format):
    articles=Article.objects.filter(author=request.user)
    books =Book.objects.filter(author=request.user)
    conferences =ConferenceArticle.objects.filter(author=request.user)
    print(conferences)

    template_path = 'pdf_template.html'


    context = {'articles': articles, 'books':books,
    'conferences':conferences,'format':export_Format}

    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="result.pdf"'

    template = get_template(template_path)

    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response
#export ends-------------------------

#export as excel -------------------------------------
def create_excelSheet(request):
    '''fields from models are exported in the form of column in
    excel format'''
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="result.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('result')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Title', 'authors', 'Journal','Date','volume', 'pages','ArticleLink','Journal Type','SJR rating','Impact Factor','Peer Reviewed','DOI' ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()
    # font_style.num_format_str = 'dd/mm/yyyy'
    # style2 =xlwt.XFStyle()
    # style2.num_format_str ='dd/mm/yyyy'

    journals = Article.objects.filter(author =request.user).values_list('title', 'co_authors','journal','pub_date__year', 'volume', 'pages','article_link','journal_type','sjrRating','impactFactor','peer_reviewed','DOI')
    print("the journals are-------------")
    print(journals)

    
    for row in journals:
        row_num += 1
        for col_num in range(len(row)):
            if col_num ==5: 
                #date column
                ws.write(row_num, col_num, row[col_num], font_style)
            else:
                ws.write(row_num, col_num, row[col_num], font_style)


    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    row_num+=3 # gap of three rows


    columns = ['Title', 'Authors', 'ConferenceName ', 'Date','Volume','Pages','Link','Publisher','DOI' ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
    
    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    conferences =ConferenceArticle.objects.filter(author=request.user).values_list('title','co_authors','conference_name','pub_date__year','volume','pages','conference_link','publisher','DOI')
    for row in conferences:
        row_num += 1
        for col_num in range(len(row)):
            
            ws.write(row_num, col_num, row[col_num], font_style)
           
    wb.save(response)
    return response
    # return HttpResponse("this will be excel sheet export")

def create_BibtexSheet(request):
    articles = Article.objects.filter(author= request.user)
    print('bibtex from create bibtex')
    bib_entries = []
    conferences =ConferenceArticle.objects.filter(author =request.user)
    books =Book.objects.filter(author=request.user)
    #export works fine for now but the missing fields and the default
    #fields are yet to be worked on

    for article in articles:
        bib_item ={
            'title':article.title,
            'author':article.co_authors,
            'journal':article.journal,
            'pages':article.pages,
            'year':str(article.pub_date.year),
            'ID':str(article.journal_ID),
            'ENTRYTYPE': 'article'

        }
        if article.volume!=0:
            bib_item['volume'] =str(article.volume)
        if article.pages !='':
            bib_item['pages'] =article.pages
        if article.publisher !='':
            bib_item['publisher'] =article.publisher

        bib_entries.append(bib_item.copy())
    
    for conference in conferences:
        bib_item={
            
            'title':conference.title,
            'author':conference.co_authors,
            'book_title':conference.conference_name,
            'year':str(conference.pub_date.year),
            'ID':conference.conference_ID,
            'ENTRYTYPE': 'inproceedings'

        }
        if conference.volume!=0:
            bib_item['volume'] =str(conference.volume)
        if conference.pages !='':
            bib_item['pages'] =conference.pages
        
        bib_entries.append(bib_item.copy())
    
    for book in books:
        bib_item={
            
            'title':book.title,
            'author':book.co_authors,
            'pages':book.pages,
            'year':str(book.pub_date.year),
            'ID':book.book_ID,
            'ENTRYTYPE': 'book'

        }
        if book.pages !='':
            bib_item['pages'] =book.pages
        bib_entries.append(bib_item.copy())

    db = BibDatabase()
    db.entries = bib_entries
    # [
    #     {'journal': 'Nice Journal',
    #     'comments': 'A comment',
    #     'pages': '12--23',
    #     'title': 'An amazing title',
    #     'year': '2013',
    #     'volume': '12',
    #     'ID': 'Cesar2013',
    #     'author': 'Jean Casar',
    #     'ENTRYTYPE': 'article'}
        
    # ]

    # writer = BibTexWriter()
    # writer.write(db)
    # content = writer
    bibtex_str = bibtexparser.dumps(db)
    return HttpResponse(bibtex_str, content_type='text/plain')
    
    
    


def article_list(request):
    if request.user.is_authenticated:
       distincts = Article.objects.filter(author = request.user).values('title').annotate(slug = Max('slug'))
       articles = Article.objects.filter(slug__in = [item['slug'] for item in distincts])

       distincts = Book.objects.filter(author = request.user).values('title').annotate(slug = Max('slug'))
       books = Book.objects.filter(slug__in = [item['slug'] for item in distincts])


       distincts = ConferenceArticle.objects.filter(author=request.user).values('title').annotate(slug = Max('slug'))
       conference_articles = ConferenceArticle.objects.filter(slug__in = [item['slug'] for item in distincts])

       distincts = GeneralArticle.objects.filter(author = request.user).values('title').annotate(slug = Max('slug'))
       general_articles = GeneralArticle.objects.filter(slug__in = [item['slug'] for item in distincts])

    else:
        return HttpResponseRedirect(reverse("accounts:signup"))
    return render(request, 'articleslist.html', {'articles': articles,
    'books':books,'conference_article':conference_articles,'general_articles':general_articles,
    })




#def article_list(request):
#    if request.user.is_authenticated:
#       articles = Article.objects.filter(author=request.user).order_by('pub_date')
#       books = Book.objects.filter(author =request.user)
#       conference_articles=ConferenceArticle.objects.filter(author=request.user)
#      general_articles =GeneralArticle.objects.filter(author=request.user)
#    else:
#        return HttpResponseRedirect(reverse("accounts:signup"))
#    return render(request, 'articleslist.html', {'articles': articles,
#    'books':books,'conference_article':conference_articles,'general_articles':general_articles,
#    })


@login_required(login_url='accounts:login')
def article_create(request, type):
    '''
        all form types are handled here
        form identified according to type parameter of url
        type= journal: it specifies the journal form is requested

    '''
    
    biptexForm = forms.BiptexForm()
    print("type is :"+type)
    if type == 'journal':
        print("yes it is journal")
        form = forms.CreateArticle()

    elif type == 'conference':
        form = forms.CreateConference()

    elif type == 'Book':
        form = forms.CreateBook()
    elif type =='general':
        form= forms.GeneralArticle()

    if request.method == 'POST':
        print(type)
        print("Post request")
        if type == 'journal':
            print("yes it is journal")
            form = forms.CreateArticle(request.POST)

        elif type == 'conference':
            form = forms.CreateConference(request.POST)
        elif type == 'Book':
            form = forms.CreateBook(request.POST)
        elif type == 'general':
            form = forms.GeneralArticle(request.POST)

        # form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article:list')

    return render(request, 'article_create.html', {'form': form,

DjangoBlog/articles/templates/article_create.html
{% extends 'base_layout.html' %}
{% load static %}
{% block contnet %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
  <div class="page-content page-container" id="page-content">
    <div class="padding">
      <div class="row container d-flex justify-content-center">
        <div class="col-xl-6 col-md-12">
          <div class="card user-card-full">
            <div class="row m-l-0 m-r-0">
              <div class="col-sm-4 bg-c-lite-green user-profile">
                <div class="card-block text-center text-white">
                  <div class="m-b-25">
                    <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius"
                      alt="User-Profile-Image">
                  </div>
                  <h6 class="f-w-600">{{request.user.username}}</h6>
                  <h8>Pulchowk Campus</h8>
                  <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="card-block">
                  <form action="{% url 'article:create' type  %}" method="POST" class="form-site"
                    enctype="multipart/form-data">
                    {%csrf_token%}
                    {% for field in form %}
                    <p>
                      {{ field.label_tag }}<br>
                      {{ field }}
                      {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                      {% endif %}
                      {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    </p>
                    {% endfor %}
                    <input type="submit" class="btn btn-success" value="Create">
                  </form>
                </div>
                <ul class="social-link list-unstyled m-t-40 m-b-10">
                  <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook"
                      data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook"
                        aria-hidden="true"></i></a></li>
                  <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter"
                      data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter"
                        aria-hidden="true"></i></a></li>
                  <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                      data-original-title="instagram" data-abc="true"><i
                        class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</body>

</html>
{% endblock %}

DjangoBlog/articles/templates/article_obj.html
{% extends 'base_layout.html' %}
{% load static %}
{% block contnet %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/article_obj.css' %}">

</head>

<body>

  <div class="main-container">
    {% for article in articles %}
    <div class="cards">
      <div class="card card-1">
       

        <h2 class="card__title">
          
          <div class='article'>
            <h2>{{article.title}} <small>{{article.version}}</small></h2>
            <p><span class="article-headings"> Authors:</span>{{article.getAuthors}}</p>

            {% if article.journal %}
            <p><span class="article-headings">Journal:</span>{{article.journal}}</p>
            {% endif %}

            <p><span class="article-headings">Description:</span>{{article.description}}</p>
            <p><span class="article-headings">Date:</span> {{article.pub_date.year}}</p>

            {% ifnotequal article.volume 0 %}
            <p><span class="article-headings">Volume:</span> {{article.volume}}</p>
            {% endifnotequal %}

            {% ifnotequal article.page '' %}
            <p><span class="article-headings">Pages:</span>{{article.pages}}</p>
            {% endifnotequal %}

            {% if article.citations %}
            <p><span class="article-headings">Citations:</span>{{article.citations}}</p>
            {% endif %}

            {% if article.publisher %}
            <p><span class="article-headings">Publisher:</span>{{article.publisher}}</p>
            {% endif %}

            {% ifnotequal article.DOI '' %}
            <p><span class="article-headings">DOI:</span>{{article.DOI}}</p>
            {% endifnotequal %}

            {% if article.journal_type %}
            <p><span class="article-headings">Type:</span>{{article.journal_type}}</p>
            {% endif %}

            {% if article.impactFactor %}
            {% ifnotequal article.impactFactor 0 %}
            <p><span class="article-headings">Impact Factor:</span>{{article.impactFactor}}</p>
            {% endifnotequal %}
            {% endif %}

            {% if article.sjrRating %}
            {% ifnotequal article.sjrRating 0 %}
            <p><span class="article-headings">SJR Rating:</span>{{article.sjrRating}} {{article.quartile}}</p>
            {% endifnotequal %}
            {% endif %}

            {% if article.peer_reviewed %}
            <p><span class="article-headings">Is peer reviewed:</span>{{article.peer_reviewed}}</p>
            {% endif %}



            {% if article.edition %}
            <p><span class="article-headings">Edition</span>{{article.edition}}</p>
            {% endif %}
            {% if article.isbn %}
            <p><span class="article-headings">ISBN</span>{{article.isbn}}</p>
            {% endif %}


            {% if article.conference_name %}
            <p><span class="article-headings">Book title</span><span
                class="article-body">{{article.conference_name}}</span></p>
            {% endif %}







          </div>
         


        </h2>
        <p class="card__apply">
        
          <a class="card__link" href="{% url 'article:edit-data' type=type slug=article.slug %}">Edit<i class="fas fa-arrow-right"></i></a>
           
          {% if article.article_link %} <a class="card__link" href="{{article.article_link}} class = " link-info">View<i
              class="fas fa-arrow-right"></i></a>
          {% else %}
          <a class="card__link" href="#">View<i class="fas fa-arrow-right"></i></a>
          {% endif %}
        </p>
      </div>



    </div>
    {%endfor%}

  </div>
</body>

</html>
{% endblock %}

DjangoBlog/articles/templates/articleslist.html
{% extends 'base_layout.html' %}
{% load static %}

{% block contnet %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/article.css' %}">

</head>

<body>

    {%for article in articles%}
    <div class='article'>

        <h2><a href="{% url 'article:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p>{{article.getAuthors}}</p>
        <p>{{article.journal}} {{article.pages}}</p>
        <p class="card__apply">
        <a class="card__link" href="{% url 'article:update_data' type='article' slug=article.slug %}">Update<i class="fas fa-arrow-right"></i></a>
        <a class="card__link" href="{% url 'article:delete-data' type='article' slug=article.slug %}">Delete<i class="fas fa-times"></i></a>
        </p>
    </div>
    
    {%endfor%}
    {%for book in books%}
    <div class='article'>

        <h2><a href="{% url 'article:detail' slug=book.slug %}">{{book.title}}</a></h2>
        <p>{{book.getAuthors}}</p>
        <p> {{book.pages}}</p>
        <p class="card__apply">
        <a class="card__link" href="{% url 'article:update_data' type='book' slug=book.slug %}">Update<i class="fas fa-arrow-right"></i></a>
        <a class="card__link" href="{% url 'article:delete-data' type='book' slug=book.slug %}">Delete<i class="fas fa-times"></i></a>
        </p>
    </div>
    {%endfor%}

    {%for article in conference_article %}
    <div class='article'>

        <h2><a href="{% url 'article:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p style="overflow: hidden;">{{article.getAuthors}}</p>
        <p>{{article.conference_name}}, {{article.pages}}</p>
        <p class="card__apply">
        <a class="card__link" href="{% url 'article:update_data' type='conference' slug=article.slug %}">Update<i class="fas fa-arrow-right"></i></a>
        <a class="card__link" href="{% url 'article:delete-data' type='conference' slug=article.slug %}">Delete<i class="fas fa-times"></i></a>
    </p>
    </div>
    {%endfor%}
    {%for article in general_articles %}
    <div class='article'>

        <h2><a href="{% url 'article:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p style="overflow: hidden;">{{article.getAuthors}}</p>
        <p>{{article.conference_name}}, {{article.pages}}</p>
        <p class="card__apply">
        <a class="card__link" href="{% url 'article:update_data' type='general' slug=article.slug %}">Update<i class="fas fa-arrow-right"></i></a>
        <a class="card__link" href="{% url 'article:delete-data' type='general' slug=article.slug %}">Delete<i class="fas fa-times"></i></a>
    </p>
    </div>
    {%endfor%}

    </div>

</body>

</html>

{% endblock %}

DjangoBlog/articles/templates/bibtexForm.html
{% extends 'base_layout.html' %}
{% load static %}

{% block contnet %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">

</head>

<body>
	<div class="bibtex-upload-form">
		<p>Choose Bibtex</p>
		<form action="{% url 'article:bibtex-upload' %}" method="POST" class="form-site" enctype="multipart/form-data">
			{%csrf_token%}
			{{biptex}}
			<input type="submit" name="bibtexUpload" class="btn btn-secondary" value="Populate">
		</form>
	</div>

</body>

</html>

{% endblock %}

DjangoBlog/articles/templates/edit.html
{% extends 'base_layout.html' %}
{% load static %}
{% block contnet %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
	<div class="page-content page-container" id="page-content">
		<div class="padding">
			<div class="row container d-flex justify-content-center">
				<div class="col-xl-6 col-md-12">
					<div class="card user-card-full">
						<div class="row m-l-0 m-r-0">
							<div class="col-sm-4 bg-c-lite-green user-profile">
								<div class="card-block text-center text-white">
									<div class="m-b-25">
										<img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius"
											alt="User-Profile-Image">
									</div>
									<h6 class="f-w-600">{{request.user.username}}</h6>
									<p>Pulchowk Campus</p>
									<i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
								</div>
							</div>
							<div class="col-sm-8">
								<div class="card-block">
									<form action="{% url 'article:edit-data' type=type slug=slug %}" method="POST"
										class="form-site" enctype="multipart/form-data">
										{%csrf_token%}
										{% for hidden in form.hidden_fields %}
										{{hidden}}
										{% endfor %}
										{% for field in form.visible_fields %}
										<p>
											{{ field.label_tag }}<br>
											{{ field }}
											{% if field.help_text %}
											<small style="color: grey">{{ field.help_text }}</small>
											{% endif %}
											{% for error in field.errors %}
										<p style="color: red">{{ error }}</p>
										{% endfor %}
										</p>
										{% endfor %}
										<input type="submit" class="btn btn-success" value="submit">
									</form>
								</div>
								<ul class="social-link list-unstyled m-t-40 m-b-10">
									<li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
											data-original-title="facebook" data-abc="true"><i
												class="mdi mdi-facebook feather icon-facebook facebook"
												aria-hidden="true"></i></a></li>
									<li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
											data-original-title="twitter" data-abc="true"><i
												class="mdi mdi-twitter feather icon-twitter twitter"
												aria-hidden="true"></i></a></li>
									<li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
											data-original-title="instagram" data-abc="true"><i
												class="mdi mdi-instagram feather icon-instagram instagram"
												aria-hidden="true"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</body>

</html>
{% endblock %}

DjangoBlog/articles/templates/profile.html
{% extends 'base_layout.html' %}
{% load static %}

{% block contnet %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  
  <div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25">
                                    <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius"
                                        alt="User-Profile-Image">
                                </div>
                                <h6 class="f-w-600">{{request.user.username}}</h6>
                                <h8>Pulchowk Campus</h8>
                                <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">{{request.user.email}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">First Name</p>
                                        <h6 class="text-muted f-w-400">{{request.user.first_name}}</h6>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Projects</h6>
                                <div class="row">
                                   
                                    <div class="col-sm-6">
                                       
                                    </div>
                                </div>
                                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

{% endblock %}

DjangoBlog/articles/templates/update.html
{% extends 'base_layout.html' %}
{% load static %}
{% block contnet %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
  <div class="page-content page-container" id="page-content">
    <div class="padding">
      <div class="row container d-flex justify-content-center">
        <div class="col-xl-6 col-md-12">
          <div class="card user-card-full">
            <div class="row m-l-0 m-r-0">
              <div class="col-sm-4 bg-c-lite-green user-profile">
                <div class="card-block text-center text-white">
                  <div class="m-b-25">
                    <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius"
                      alt="User-Profile-Image">
                  </div>
                  <h6 class="f-w-600">{{request.user.username}}</h6>
                  <h8>Pulchowk Campus</h8>
                  <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="card-block">
					<form action="{% url 'article:update_data' type=type slug=slug %}"  method="POST" class="form-site" enctype="multipart/form-data">
						{%csrf_token%}
						{% for hidden in form.hidden_fields %}
						{{hidden}}
						{% endfor %}
						{% for field in form.visible_fields %}
						<p>
						  {{ field.label_tag }}<br>
						  {{ field }}
						  {% if field.help_text %}
							<small style="color: grey">{{ field.help_text }}</small>
						  {% endif %}
						  {% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						  {% endfor %}
						</p>
						  {% endfor %}
						<input type="submit" class="btn btn-success" value="submit">
						</form>
                </div>
                <ul class="social-link list-unstyled m-t-40 m-b-10">
                  <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook"
                      data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook"
                        aria-hidden="true"></i></a></li>
                  <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter"
                      data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter"
                        aria-hidden="true"></i></a></li>
                  <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title=""
                      data-original-title="instagram" data-abc="true"><i
                        class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</body>

</html>
{% endblock %}